final_answer_task:
  description: >
    이미지 분석가 : {image_result}
    본문 분석가 : {context_result}
    테이블 분석가 : {table_result}
    주어진 답변들을 종합하여 질문에 대한 최종 답변을 도출하세요.
    만약 생성된 이미지의 이름이 있다면 반드시 표기하세요.
    받은 답변들을 하나의 답변으로 종합하여 출력하세요.
    생성된 이미지 이름은 반드시 답변을 다 끝내고 마지막에 모아서 파일 이름을 표기하세요.
    반드시 예시와 같은 출력 형식으로 내보내세요.
    
  expected_output: >
    [출력 형식]
    질문에 대한 답변에 내용을 작성

    [생성된 이미지 이름]\n
    - 생성된 이미지 이름.png

    예시)
    네이버의 2024년 다양한 투자를 통해 매출을 상승시켰습니다.

    [생성된 이미지 이름]\n
    - naver_financial.png

    예시)
    SK하이닉스는 이번년도 반도체 부분에 많은 투자를 진행하였으며, 좋은 성과를 이루었습니다.

    [생성된 이미지 이름]\n
    - naver_financial.png
    
    
  agent: final_answerman